"""
patterns.py - Error pattern definitions for Nextflow log analysis.
Each pattern: id, label, compiled regexes, severity, icon, cause, fix, command.
"""
import re

REQUIRED_COLUMNS = ["sample", "fastq_1", "fastq_2", "strandedness"]
VALID_STRANDEDNESS = ["forward", "reverse", "unstranded", "auto"]

ERROR_PATTERNS = [
    {
        "id": "memory_exceeded",
        "label": "Memory Exceeded",
        "patterns": [
            re.compile(r"Process requirement exceeds available memory", re.I),
            re.compile(r"java\.lang\.OutOfMemoryError", re.I),
            re.compile(r"Cannot allocate memory", re.I),
            re.compile(r"oom-kill", re.I),
            re.compile(r"Killed\s+process", re.I),
            re.compile(r"memory limit", re.I),
            re.compile(r"SIGKILL", re.I),
            re.compile(r"exceeded memory", re.I),
        ],
        "severity": "critical",
        "icon": "\U0001f9e0",
        "cause": "Process requires more RAM than allocated or available on the execution node.",
        "fix": "Increase memory in nextflow.config (e.g., process { memory = '16.GB' }), use a larger instance, or enable retry with errorStrategy 'retry' and maxRetries 3.",
        "command": "# In nextflow.config:\nprocess {\n  memory = { 8.GB * task.attempt }\n  errorStrategy = 'retry'\n  maxRetries = 3\n}",
    },
    {
        "id": "missing_file",
        "label": "Missing File",
        "patterns": [
            re.compile(r"No such file or directory", re.I),
            re.compile(r"FileNotFoundException", re.I),
            re.compile(r"Missing (input|output) file", re.I),
            re.compile(r"Path does not exist", re.I),
            re.compile(r"Unable to access", re.I),
            re.compile(r"file not found", re.I),
        ],
        "severity": "critical",
        "icon": "\U0001f4c1",
        "cause": "An expected input file, reference, or index is missing or the path is incorrect.",
        "fix": "Verify file paths in your sample sheet and config. Check that reference genomes and indices exist. Ensure symlinks are valid.",
        "command": "# Check file existence:\nls -la /path/to/missing/file\n\n# Verify sample sheet paths:\nawk -F',' '{print $2}' samplesheet.csv | while read f; do\n  [ ! -f \"$f\" ] && echo \"MISSING: $f\"\ndone",
    },
    {
        "id": "container_issue",
        "label": "Container / Environment Issue",
        "patterns": [
            re.compile(r"Unable to pull (image|container)", re.I),
            re.compile(r"docker.*not found", re.I),
            re.compile(r"singularity.*error", re.I),
            re.compile(r"Container.*failed", re.I),
            re.compile(r"OCI runtime", re.I),
            re.compile(r"permission denied.*docker", re.I),
            re.compile(r"FATAL.*container", re.I),
            re.compile(r"Failed to create Conda environment", re.I),
            re.compile(r"CondaError", re.I),
            re.compile(r"conda.*create.*failed", re.I),
            re.compile(r"mamba.*error", re.I),
            re.compile(r"Failed to create.*environment", re.I),
        ],
        "severity": "high",
        "icon": "\U0001f433",
        "cause": "Docker/Singularity container or Conda/Mamba environment failed to pull, create, or execute.",
        "fix": "For containers: check the engine is installed and running, verify network access. For Conda/Mamba: check conda is installed, channels are reachable, and there are no dependency conflicts. Try creating the environment manually first.",
        "command": "# Test container pull:\ndocker pull nfcore/rnaseq:latest\n# Or Singularity:\nsingularity pull docker://nfcore/rnaseq:latest\n\n# Test Conda environment:\nconda create -n test_env bioconda::star\n# Check Conda config:\nconda config --show channels\nconda info",
    },
    {
        "id": "reference_index",
        "label": "Reference / Index Issue",
        "patterns": [
            re.compile(r"genome index", re.I),
            re.compile(r"STAR.*genomeGenerate", re.I),
            re.compile(r"hisat2-build", re.I),
            re.compile(r"bowtie2-build", re.I),
            re.compile(r"faidx", re.I),
            re.compile(r"\.fai.*not found", re.I),
            re.compile(r"index.*missing", re.I),
            re.compile(r"incompatible genome", re.I),
        ],
        "severity": "high",
        "icon": "\U0001f9ec",
        "cause": "Reference genome index is missing, incompatible, or corrupted.",
        "fix": "Rebuild the genome index with the correct tool version. Ensure reference FASTA matches the index.",
        "command": "# Rebuild STAR index:\nSTAR --runMode genomeGenerate \\\n  --genomeDir /path/to/star_index \\\n  --genomeFastaFiles /path/to/genome.fa \\\n  --sjdbGTFfile /path/to/genes.gtf\n\n# Rebuild samtools index:\nsamtools faidx genome.fa",
    },
    {
        "id": "permission_issue",
        "label": "Permission Denied",
        "patterns": [
            re.compile(r"Permission denied", re.I),
            re.compile(r"Operation not permitted", re.I),
            re.compile(r"Access denied", re.I),
            re.compile(r"cannot open.*permission", re.I),
            re.compile(r"EACCES", re.I),
        ],
        "severity": "high",
        "icon": "\U0001f512",
        "cause": "Insufficient file system permissions to read inputs, write outputs, or execute binaries.",
        "fix": "Check ownership and permissions on work dir, output dir, and input files.",
        "command": "# Fix work directory permissions:\nchmod -R 755 work/\nchown -R $USER:$GROUP work/\n\n# Check output directory:\nls -la results/",
    },
    {
        "id": "failed_process",
        "label": "Failed Process",
        "patterns": [
            re.compile(r"Process.*terminated with.*exit status [^0]", re.I),
            re.compile(r"Command exit status: [^0]", re.I),
            re.compile(r"Error executing process", re.I),
            re.compile(r"Task.*failed", re.I),
            re.compile(r"exit code [^0]", re.I),
            re.compile(r"non-zero exit", re.I),
        ],
        "severity": "critical",
        "icon": "\U0001f4a5",
        "cause": "A pipeline process exited with a non-zero status code.",
        "fix": "Check .command.err and .command.log in the work directory for the specific tool error.",
        "command": "# Find the failed task work directory:\nnextflow log last -f workdir,name,status | grep FAILED\n\n# Check error logs:\ncat work/xx/yyyyyy/.command.err\ncat work/xx/yyyyyy/.command.log",
    },
    {
        "id": "invalid_parameter",
        "label": "Invalid Parameter",
        "patterns": [
            re.compile(r"Unknown.*parameter", re.I),
            re.compile(r"invalid.*option", re.I),
            re.compile(r"unrecognized.*argument", re.I),
            re.compile(r"not a valid", re.I),
            re.compile(r"ERROR.*params", re.I),
            re.compile(r"Schema validation", re.I),
        ],
        "severity": "medium",
        "icon": "\u2699\ufe0f",
        "cause": "An invalid or unrecognized parameter was passed to the pipeline or a tool.",
        "fix": "Review your nextflow run command and params file. Run with --help to see available options.",
        "command": "# List valid parameters:\nnextflow run nf-core/rnaseq --help\n\n# Validate params file:\nnextflow run nf-core/rnaseq -params-file params.yaml --validate_params",
    },
    {
        "id": "disk_space",
        "label": "Disk Space",
        "patterns": [
            re.compile(r"No space left on device", re.I),
            re.compile(r"Disk quota exceeded", re.I),
            re.compile(r"ENOSPC", re.I),
            re.compile(r"cannot write", re.I),
        ],
        "severity": "critical",
        "icon": "\U0001f4be",
        "cause": "The filesystem ran out of space during execution.",
        "fix": "Clean up old work directories with nextflow clean. Remove unnecessary intermediate files. Increase disk allocation.",
        "command": "# Check disk usage:\ndf -h .\ndu -sh work/\n\n# Clean old runs:\nnextflow clean -f -before last",
    },
]
